apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-k8s-curd-aws-deployment
  labels:
    app: springboot-k8s-curd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-k8s-curd
  template:
    metadata:
      labels:
        app: springboot-k8s-curd
    spec:
      containers:
      - name: springboot-k8s-curd
        image: zz19431943/springboot-k8s-curd:1.1
        ports:
        - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: springboot-k8s-curd-aws-service
spec:
  type: NodePort 
  selector:
    app: springboot-k8s-curd
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081